version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_DATABASE=task_manager
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"